apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: express-demo
  template:
    metadata:
      labels:
        app: express-demo
    spec:
      containers:
      - name: express-demo
        image: deepakbhagat/express:01

---

apiVersion: v1
kind: Service
metadata:
  name: express-service
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 3000
  selector:
    app: express-demo
  type: LoadBalancer

